name: 'tcgplayer_modeling'
version: '1.0.0'
config-version: 2

profile: 'tcgplayer_modeling'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tcgplayer_modeling:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table